# Generated by Django 5.1.6 on 2025-03-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_images/default_event.jpg', upload_to='event_images/'),
        ),
    ]
